# Reff: http://wiki.ros.org/costmap_2d
local_costmap:
    publish_frequency: 2.0
    update_frequency: 5.0

    obstacle_range: 2.5
    raytrace_range: 2.5
    static_map: false

    width: 2.5
    height: 2.5
    resolution: 0.02
    

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

    static_layer:
        enabled:              true
        map_topic:            "/map"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  5  
        inflation_radius:     0.3

